backend:
  name: github
  repo: kwonjounghun/gatsby_blog

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: _posts/blog
    category: default
    create: true
    fields:
      - { name: category, label: Category, widget: select, options: ["post", "start", "first"]}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: study
    label: Study
    folder: _posts/study
    category: default
    create: true
    fields:
      - { name: category, label: Category, widget: select, options: ["post2", "start2", "first2"]}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }